ND-271 Updated the ticket to include the functionality of updating or creating tickets

diff --git a/.github/workflows/dependabot-pr-to-jira.yml b/.github/workflows/dependabot-pr-to-jira.yml
--- a/.github/workflows/dependabot-pr-to-jira.yml
+++ b/.github/workflows/dependabot-pr-to-jira.yml
@@ -53,35 +53,34 @@ jobs:
             "$JIRA_URL/rest/api/2/search?jql=project=ND%20AND%20labels%3D%27JDTEST%27")
           
           # Check if the response is valid JSON
-               if echo "$response" | jq -e . >/dev/null 2>&1; then
-          
-          # Extract the first issue key from the response
-               issue_id=$(echo "$response" | jq -r '.issues[0].key')
+          if echo "$response" | jq -e . >/dev/null 2>&1; then
+            # Extract the first issue key from the response
+            issue_id=$(echo "$response" | jq -r '.issues[0].key')
                
-               if [ -z "$issue_id" ]; then
-               echo "No issues found with the 'JDTEST' label in project 'ND'. Creating a new issue..."
-               create_response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
-               -X POST \
-               -H "Content-Type: application/json" \
-               --data "{\"fields\":{\"project\":{\"key\":\"ND\"},\"summary\":\"Dependabot PRs\",\"description\":\"$PR_DESCRIPTION\",\"labels\":[\"jira_dependabot\"]}}" \
-               "$JIRA_URL/rest/api/2/issue")
-               new_issue_id=$(echo "$create_response" | jq -r '.key')
-               echo "Created new issue $new_issue_id"
-               echo "ISSUE_ID=$new_issue_id" >> $GITHUB_ENV
-               else
-               echo "Found issue $issue_id. Updating the description..."
-               update_response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
-               -X PUT \
-               -H "Content-Type: application/json" \
-               --data "{\"fields\":{\"description\":\"$PR_DESCRIPTION\"}}" \
-               "$JIRA_URL/rest/api/2/issue/$issue_id")
-               echo "Updated issue $issue_id"
-               echo "ISSUE_ID=$issue_id" >> $GITHUB_ENV
-               fi
-               else
-               echo "Invalid JSON response"
-               exit 1
-               fi
+            if [ -z "$issue_id" ]; then
+              echo "No issues found with the 'JDTEST' label in project 'ND'. Creating a new issue..."
+              create_response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
+                 -X POST \
+                 -H "Content-Type: application/json" \
+                 --data "{\"fields\":{\"project\":{\"key\":\"ND\"},\"summary\":\"Dependabot PRs\",\"description\":\"$PR_DESCRIPTION\",\"labels\":[\"jira_dependabot\"]}}" \
+                 "$JIRA_URL/rest/api/2/issue")
+              new_issue_id=$(echo "$create_response" | jq -r '.key')
+              echo "Created new issue $new_issue_id"
+              echo "ISSUE_ID=$new_issue_id" >> $GITHUB_ENV
+            else
+              echo "Found issue $issue_id. Updating the description..."
+              update_response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
+                 -X PUT \
+                 -H "Content-Type: application/json" \
+                 --data "{\"fields\":{\"description\":\"$PR_DESCRIPTION\"}}" \
+                 "$JIRA_URL/rest/api/2/issue/$issue_id")
+              echo "Updated issue $issue_id"
+              echo "ISSUE_ID=$issue_id" >> $GITHUB_ENV
+            fi
+          else
+            echo "Invalid JSON response"
+            exit 1
+          fi
 
 
       - name: Log created or updated issue
