ND-271 Updated the ticket to include the functionality of updating or creating tickets

diff --git a/.github/workflows/dependabot-pr-to-jira.yml b/.github/workflows/dependabot-pr-to-jira.yml
--- a/.github/workflows/dependabot-pr-to-jira.yml
+++ b/.github/workflows/dependabot-pr-to-jira.yml
@@ -48,37 +48,40 @@ jobs:
           JIRA_USERNAME: ${{ secrets.TECH_SERVICES_JIRA_EMAIL }}
         run: |
           echo "Searching for issues with the 'jira_dependabot' label in project 'ND'..."
-
+          
           # Define JQL query to find issues with the 'dependabot' label in the 'ND' project
-          JQL_QUERY="project=ND AND labels=jira_dependabot"
-
-          # URL encode the JQL query to handle special characters
-          JQL_QUERY=$(echo "$JQL_QUERY" | jq -sRr @uri)
-
+          JQL_QUERY='project="ND" AND labels="jira_dependabot"'
+          
           # Make API request to Jira to search for issues with the given label in the 'ND' project
-          response=$(curl -s -w "%{http_code}" -u $JIRA_USERNAME:$JIRA_API_TOKEN \
+          response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
             -X GET \
             -H "Content-Type: application/json" \
-            "$JIRA_URL/rest/api/3/search?jql=$JQL_QUERY")
-
-          # Extract the first issue key from the response using jq
-          issue_id=$(echo "$response" | jq -r '.issues[0].key // empty')
-
-          if [ -z "$issue_id" ]; then
-            echo "No issues found with the 'dependabot' label in project 'ND'."
+            "$JIRA_URL/rest/api/2/search?jql=$JQL_QUERY")
+          
+          # Check if the response is valid JSON
+          if echo "$response" | jq -e . >/dev/null 2>&1; then
+            # Extract the first issue key from the response
+            issue_id=$(echo $response | jq -r '.issues[0].key')
+          
+            if [ -z "$issue_id" ]; then
+              echo "No issues found with the 'jira_dependabot' label in project 'ND'."
+            else
+              echo "Found issue $issue_id"
+              echo "ISSUE_ID=$issue_id" >> $GITHUB_ENV
+            fi
           else
-            echo "Found issue $issue_id"
-            echo "ISSUE_ID=$issue_id" >> $GITHUB_ENV
-          fi
-
-      - name: Log created or updated issue
-        run: |
-          if [ -n "${{ env.ISSUE_ID }}" ]; then
-            echo "Issue ${{ env.ISSUE_ID }} was created or updated"
-          else
-            echo "Failed to create or update issue"
+            echo "Invalid JSON response"
             exit 1
           fi
+    
+          - name: Log created or updated issue
+            run: |
+              if [ -n "${{ env.ISSUE_ID }}" ]; then
+                echo "Issue ${{ env.ISSUE_ID }} was created or updated"
+              else
+                echo "Failed to create or update issue"
+                exit 1
+              fi
 
       - name: Comment on GitHub
         uses: actions/github-script@v7
