ND-271 Updated the ticket to include the functionality of updating or creating tickets

diff --git a/.github/workflows/dependabot-pr-to-jira.yml b/.github/workflows/dependabot-pr-to-jira.yml
--- a/.github/workflows/dependabot-pr-to-jira.yml
+++ b/.github/workflows/dependabot-pr-to-jira.yml
@@ -16,7 +16,6 @@ jobs:
     runs-on: ubuntu-latest
     name: Create or Update Jira Ticket
     steps:
-
       - name: List open Dependabot PRs on main branch
         id: list-prs
         env:
@@ -56,7 +55,7 @@ jobs:
           if echo "$response" | jq -e . >/dev/null 2>&1; then
             # Extract the first issue key from the response
             issue_id=$(echo "$response" | jq -r '.issues[0].key')
-               
+          
             if [ -z "$issue_id" ]; then
               echo "No issues found with the 'JDTEST' label in project 'ND'. Creating a new issue..."
               create_response=$(curl -s -u $JIRA_USERNAME:$JIRA_API_TOKEN \
@@ -82,15 +81,14 @@ jobs:
             exit 1
           fi
 
-
       - name: Log created or updated issue
         run: |
-              if [ -n "${{ env.ISSUE_ID }}" ]; then
-                echo "Issue ${{ env.ISSUE_ID }} was created or updated"
-              else
-                echo "Failed to create or update issue"
-                exit 1
-              fi
+          if [ -n "${{ env.ISSUE_ID }}" ]; then
+            echo "Issue ${{ env.ISSUE_ID }} was created or updated"
+          else
+            echo "Failed to create or update issue"
+            exit 1
+          fi
 
       - name: Comment on GitHub
         uses: actions/github-script@v7
