ND-271 Updated the format of description

diff --git a/.github/workflows/dependabot-pr-to-jira.yml b/.github/workflows/dependabot-pr-to-jira.yml
--- a/.github/workflows/dependabot-pr-to-jira.yml
+++ b/.github/workflows/dependabot-pr-to-jira.yml
@@ -45,7 +45,16 @@ jobs:
         id: check-ticket
         run: |
           response=$(curl -s -u "${{ secrets.TECH_SERVICES_JIRA_EMAIL }}:${{ secrets.TECH_SERVICES_JIRA_TOKEN }}" -X GET "${{ secrets.TECH_SERVICES_JIRA_URL }}/rest/api/3/search?jql=labels=Dependabot AND project=ND AND summary~'${{ github.repository }}'")
+          if [ $? -ne 0 ]; then
+          echo "Failed to query Jira API"
+          exit 1
+          fi
           issue_key=$(echo $response | jq -r '.issues[0].key // empty')
+          if [ -z "$issue_key" ]; then
+          echo "No existing Jira ticket found"
+          else
+          echo "Found existing Jira ticket: $issue_key"
+          fi
           echo "issue_key=$issue_key" >> $GITHUB_ENV
 
       - name: Create or Update Jira Ticket
